//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CleanS.CleanS
{

    public partial class ContractDet : BaseObject
    {
        int fIdContractDet;
        [Key(true)]
        public int IdContractDet
        {
            get { return fIdContractDet; }
            set { SetPropertyValue<int>("IdContractDet", ref fIdContractDet, value); }
        }
        Contract fIdContract;
        [Association(@"ContractDetReferencesContract")]
        public Contract IdContract
        {
            get { return fIdContract; }
            set { SetPropertyValue<Contract>("IdContract", ref fIdContract, value); }
        }
        Service fIdService;
        [Association(@"ContractDetReferencesService")]
        public Service IdService
        {
            get { return fIdService; }
            set { SetPropertyValue<Service>("IdService", ref fIdService, value); }
        }
        double fHours;
        public double Hours
        {
            get { return fHours; }
            set { SetPropertyValue<double>("Hours", ref fHours, value); }
        }
        int fIsNotCompleted;
        public int IsNotCompleted
        {
            get { return fIsNotCompleted; }
            set { SetPropertyValue<int>("IsNotCompleted", ref fIsNotCompleted, value); }
        }
    }

}
