//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{
    [MetadataType(typeof(ContractMetaData))]
    public partial class Contract : BaseObject
    {
        int fIdContract;
        [DevExpress.Xpo.Key(true)]
        public int IdContract
        {
            get { return fIdContract; }
            set { SetPropertyValue<int>("IdContract", ref fIdContract, value); }
        }
        Customer fIdCustomer;
        [DevExpress.Xpo.Association(@"ContractReferencesCustomer")]
        public Customer IdCustomer
        {
            get { return fIdCustomer; }
            set { SetPropertyValue<Customer>("IdCustomer", ref fIdCustomer, value); }
        }
        DateTime fCreateDate;
        public DateTime CreateDate
        {
            get { return fCreateDate; }
            set { SetPropertyValue<DateTime>("CreateDate", ref fCreateDate, value); }
        }
        double fHours;
        public double Hours
        {
            get { return fHours; }
            set { SetPropertyValue<double>("Hours", ref fHours, value); }
        }
        [DevExpress.Xpo.Association(@"ContractDetReferencesContract")]
        public XPCollection<ContractDet> ContractDets { get { return GetCollection<ContractDet>("ContractDets"); } }
        [DevExpress.Xpo.Association(@"ContractEmployeeReferencesContract")]
        public XPCollection<ContractEmployee> ContractEmployees { get { return GetCollection<ContractEmployee>("ContractEmployees"); } }
    }

}
