//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CleanS.CleanS
{

    public partial class ContractEmployee : BaseObject
    {
        int fIdContractEmployee;
        [Key(true)]
        public int IdContractEmployee
        {
            get { return fIdContractEmployee; }
            set { SetPropertyValue<int>("IdContractEmployee", ref fIdContractEmployee, value); }
        }
        Contract fIdContract;
        [Association(@"ContractEmployeeReferencesContract")]
        public Contract IdContract
        {
            get { return fIdContract; }
            set { SetPropertyValue<Contract>("IdContract", ref fIdContract, value); }
        }
        Employee fIdEmployee;
        [Association(@"ContractEmployeeReferencesEmployee")]
        public Employee IdEmployee
        {
            get { return fIdEmployee; }
            set { SetPropertyValue<Employee>("IdEmployee", ref fIdEmployee, value); }
        }
    }

}
