//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{
    [MetadataType(typeof(CustomerMetaData))]
    public partial class Customer : BaseObject // XPLiteObject
    {
        int fIdCustomer;
        [DevExpress.Xpo.Key(true)]
        public int IdCustomer
        {
            get { return fIdCustomer; }
            set { SetPropertyValue<int>("IdCustomer", ref fIdCustomer, value); }
        }
        string fFirstName;
        [Size(50)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fLastName;
        [Size(50)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fVat;
        [Size(9)]
        public string Vat
        {
            get { return fVat; }
            set { SetPropertyValue<string>("Vat", ref fVat, value); }
        }
        string fDoy;
        [Size(50)]
        public string Doy
        {
            get { return fDoy; }
            set { SetPropertyValue<string>("Doy", ref fDoy, value); }
        }
        string fCompanyName;
        [Size(50)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>("CompanyName", ref fCompanyName, value); }
        }
        [DevExpress.Xpo.Association(@"ContractReferencesCustomer")]
        public XPCollection<Contract> Contracts { get { return GetCollection<Contract>("Contracts"); } }
    }

}
