//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{

    [MetadataType(typeof(EmployeeGroupMetaData))]
    public partial class EmployeeGroup : BaseObject
    {
        int fIdEmployeeGroup;
        [DevExpress.Xpo.Key(true)]
        public int IdEmployeeGroup
        {
            get { return fIdEmployeeGroup; }
            set { SetPropertyValue<int>("IdEmployeeGroup", ref fIdEmployeeGroup, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        //[Association(@"EmployeeReferencesEmployeeGroup")]
        //public XPCollection<Employee> Employees { get { return GetCollection<Employee>("Employees"); } }
    }

}
