//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using CleanS.Infrastructure;

namespace CleanS.CleanS
{
    public class EmployeeCompMetaData
    {
        [Struct.CustomDisplayName("EmployeeCompId", "IdEmployeeComp")]
        [ReadOnly(true)]
        public int IdEmployeeComp { get; set; }

        [Struct.CustomDisplayName("EmployeeCompDescription", "Description")]
        public string Description { get; set; }

        [Struct.CustomDisplayName("EmployeeCompSum", "Sum")]
        public double Sum { get; set; }

    }
}