//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using CleanS.Infrastructure;

namespace CleanS.CleanS
{
    public class EmployeeGroupMetaData
    {
        [Struct.CustomDisplayName("EmployeeGroupId", "IdEmployeeGroup")]
        [ReadOnly(true)]
        public int IdEmployeeGroup { get; set; }

        [Struct.CustomDisplayName("EmployeeGroupDescription", "Description")]
        public string Description { get; set; }

    }
}