//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{

    [MetadataType(typeof(EmployeeMetaData))]
    public partial class Employee : BaseObject
    {
        int fIdEmployee;
        [DevExpress.Xpo.Key(true)]
        public int IdEmployee
        {
            get { return fIdEmployee; }
            set { SetPropertyValue<int>("IdEmployee", ref fIdEmployee, value); }
        }
        string fFirstName;
        [Size(50)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>("FirstName", ref fFirstName, value); }
        }
        string fLastName;
        [Size(50)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>("LastName", ref fLastName, value); }
        }
        string fVat;
        [Size(9)]
        public string Vat
        {
            get { return fVat; }
            set { SetPropertyValue<string>("Vat", ref fVat, value); }
        }
        string fDoy;
        [Size(50)]
        public string Doy
        {
            get { return fDoy; }
            set { SetPropertyValue<string>("Doy", ref fDoy, value); }
        }

        private EmployeeComp fIdEmployeeComp;
        public EmployeeComp IdEmployeeComp
        {
            get { return fIdEmployeeComp; }
            set { SetPropertyValue<EmployeeComp>("IdEmployeeComp", ref fIdEmployeeComp, value); }
        }

        private EmployeeGroup fIdEmployeeGroup;
        public EmployeeGroup IdEmployeeGroup
        {
            get { return fIdEmployeeGroup; }
            set { SetPropertyValue<EmployeeGroup>("IdEmployeeGroup", ref fIdEmployeeGroup, value); }
        }

        double fWage;
        public double Wage
        {
            get { return fWage; }
            set { SetPropertyValue<double>("Wage", ref fWage, value); }
        }

        [DevExpress.Xpo.Association(@"ContractEmployeeReferencesEmployee")]
        public XPCollection<ContractEmployee> ContractEmployees { get { return GetCollection<ContractEmployee>("ContractEmployees"); } }
    }

}
