//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace CleanS.CleanS
{

    public partial class EntityDet : XPLiteObject
    {
        int fIdEntityDet;
        [Key(true)]
        public int IdEntityDet
        {
            get { return fIdEntityDet; }
            set { SetPropertyValue<int>("IdEntityDet", ref fIdEntityDet, value); }
        }
        int fEntityId;
        public int EntityId
        {
            get { return fEntityId; }
            set { SetPropertyValue<int>("EntityId", ref fEntityId, value); }
        }
        int fIdActualEntity;
        public int IdActualEntity
        {
            get { return fIdActualEntity; }
            set { SetPropertyValue<int>("IdActualEntity", ref fIdActualEntity, value); }
        }
        int fIdType;
        public int IdType
        {
            get { return fIdType; }
            set { SetPropertyValue<int>("IdType", ref fIdType, value); }
        }
        int fIdDetail;
        public int IdDetail
        {
            get { return fIdDetail; }
            set { SetPropertyValue<int>("IdDetail", ref fIdDetail, value); }
        }
        string fValue;
        public string Value
        {
            get { return fValue; }
            set { SetPropertyValue<string>("Value", ref fValue, value); }
        }
    }

}
