//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{
    [MetadataType(typeof(PriceListMetaData))]
    public partial class PriceList : BaseObject
    {
        int fIdPriceList;
        [DevExpress.Xpo.Key(true)]
        public int IdPriceList
        {
            get { return fIdPriceList; }
            set { SetPropertyValue<int>("IdPriceList", ref fIdPriceList, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>("Amount", ref fAmount, value); }
        }
        [DevExpress.Xpo.Association(@"ServiceReferencesPriceList")]
        public XPCollection<Service> Services { get { return GetCollection<Service>("Services"); } }
    }

}
