//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CleanS.CleanS
{
    [MetadataType(typeof(ServiceMetaData))]
    public partial class Service : BaseObject
    {
        int fIdService;
        [DevExpress.Xpo.Key(true)]
        public int IdService
        {
            get { return fIdService; }
            set { SetPropertyValue<int>("IdService", ref fIdService, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }

        PriceList fIdPriceList;
        [DevExpress.Xpo.Association(@"ServiceReferencesPriceList")]
        public PriceList IdPriceList
        {
            get { return fIdPriceList; }
            set { SetPropertyValue<PriceList>("IdPriceList", ref fIdPriceList, value); }
        }

        [DevExpress.Xpo.Association(@"ContractDetReferencesService")]
        public XPCollection<ContractDet> ContractDets { get { return GetCollection<ContractDet>("ContractDets"); } }
    }

}
