//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCleanS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCleanS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanS.ResourceCleanS", typeof(ResourceCleanS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημερομηνία Συμβολαίου.
        /// </summary>
        internal static string ContractCreateDate {
            get {
                return ResourceManager.GetString("ContractCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Πελάτη.
        /// </summary>
        internal static string ContractCustomerId {
            get {
                return ResourceManager.GetString("ContractCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ωρες Συμβολαίου.
        /// </summary>
        internal static string ContractHours {
            get {
                return ResourceManager.GetString("ContractHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Συμβολαίου.
        /// </summary>
        internal static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΑΦΜ.
        /// </summary>
        internal static string CustomerAfm {
            get {
                return ResourceManager.GetString("CustomerAfm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επωνυμία.
        /// </summary>
        internal static string CustomerCompany {
            get {
                return ResourceManager.GetString("CustomerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔΟΥ.
        /// </summary>
        internal static string CustomerDoy {
            get {
                return ResourceManager.GetString("CustomerDoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα.
        /// </summary>
        internal static string CustomerFirstName {
            get {
                return ResourceManager.GetString("CustomerFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Πελάτη.
        /// </summary>
        internal static string CustomerId {
            get {
                return ResourceManager.GetString("CustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επώνυμο.
        /// </summary>
        internal static string CustomerLastName {
            get {
                return ResourceManager.GetString("CustomerLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        internal static string EmployeeCompDescription {
            get {
                return ResourceManager.GetString("EmployeeCompDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Κατηγορίας.
        /// </summary>
        internal static string EmployeeCompId {
            get {
                return ResourceManager.GetString("EmployeeCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ποσό.
        /// </summary>
        internal static string EmployeeCompSum {
            get {
                return ResourceManager.GetString("EmployeeCompSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΔΟΥ.
        /// </summary>
        internal static string EmployeeDoy {
            get {
                return ResourceManager.GetString("EmployeeDoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα.
        /// </summary>
        internal static string EmployeeFirstName {
            get {
                return ResourceManager.GetString("EmployeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        internal static string EmployeeGroupDescription {
            get {
                return ResourceManager.GetString("EmployeeGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Ομάδας.
        /// </summary>
        internal static string EmployeeGroupId {
            get {
                return ResourceManager.GetString("EmployeeGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Υπαλλήλου.
        /// </summary>
        internal static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία Ωρομισθίου.
        /// </summary>
        internal static string EmployeeIdEmployeeComp {
            get {
                return ResourceManager.GetString("EmployeeIdEmployeeComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία Ομάδας.
        /// </summary>
        internal static string EmployeeIdEmployeeGroup {
            get {
                return ResourceManager.GetString("EmployeeIdEmployeeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επώνυμο.
        /// </summary>
        internal static string EmployeeLastName {
            get {
                return ResourceManager.GetString("EmployeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΑΦΜ.
        /// </summary>
        internal static string EmployeeVat {
            get {
                return ResourceManager.GetString("EmployeeVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ωρομίσθιο.
        /// </summary>
        internal static string EmployeeWage {
            get {
                return ResourceManager.GetString("EmployeeWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ποσό.
        /// </summary>
        internal static string PriceListAmount {
            get {
                return ResourceManager.GetString("PriceListAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Τιμοκαταλόγου.
        /// </summary>
        internal static string PriceListId {
            get {
                return ResourceManager.GetString("PriceListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        internal static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κωδικός Υπηρεσίας.
        /// </summary>
        internal static string ServiceId {
            get {
                return ResourceManager.GetString("ServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τιμοκατάλογος Υπηρεσίας.
        /// </summary>
        internal static string ServiceIdPriceList {
            get {
                return ResourceManager.GetString("ServiceIdPriceList", resourceCulture);
            }
        }
    }
}
